from . import test_bilingual_templates
from . import test_currency_render
from . import test_golden_snapshots
from . import test_multi_company
from . import test_numeral_resolution
from . import test_render_performance
from . import test_rtl_layout_render
from . import test_secondary_language
from . import test_visual_hash_snapshots
